# 应用服务 WEB 访问端口
server:
  port: 15001

# 应用名称
spring:
  application:
    name: mybatis-generator
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: gin
    # 数据库连接地址
    url: jdbc:mysql://123.60.148.210:3306/vue2_gin?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true

    # 数据库用户名&密码：
    username: root1111
    password: 123456

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mapper/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.upking.mybatis.generator.domain.table
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
